insert into CoachedFor (TeamName, CoachID) values ('Jets', 1);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 2);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 3);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 4);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 5);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 6);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 7);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 8);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 9);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 10);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 11);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 12);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 13);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 14);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 15);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 16);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 17);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 18);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 19);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 20);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 21);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 22);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 23);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 24);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 25);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 26);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 27);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 28);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 29);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 30);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 31);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 32);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 33);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 34);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 35);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 36);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 37);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 38);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 39);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 40);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 41);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 42);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 43);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 44);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 45);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 46);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 47);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 48);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 49);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 50);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 51);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 52);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 53);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 54);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 55);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 56);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 57);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 58);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 59);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 60);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 61);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 62);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 63);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 64);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 65);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 66);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 67);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 68);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 69);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 70);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 71);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 72);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 73);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 74);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 75);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 76);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 77);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 78);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 79);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 80);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 81);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 82);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 83);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 84);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 85);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 86);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 87);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 88);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 89);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 90);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 91);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 92);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 93);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 94);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 95);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 96);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 97);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 98);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 99);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 100);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 101);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 102);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 103);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 104);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 105);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 106);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 107);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 108);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 109);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 110);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 111);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 112);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 113);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 114);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 115);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 116);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 117);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 118);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 119);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 120);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 121);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 122);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 123);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 124);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 125);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 126);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 127);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 128);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 129);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 130);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 131);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 132);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 133);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 134);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 135);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 136);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 137);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 138);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 139);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 140);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 141);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 142);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 143);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 144);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 145);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 146);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 147);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 148);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 149);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 150);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 151);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 152);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 153);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 154);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 155);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 156);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 157);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 158);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 159);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 160);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 161);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 162);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 163);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 164);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 165);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 166);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 167);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 168);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 169);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 170);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 171);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 172);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 173);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 174);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 175);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 176);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 177);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 178);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 179);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 180);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 181);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 182);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 183);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 184);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 185);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 186);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 187);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 188);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 189);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 190);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 191);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 192);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 193);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 194);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 195);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 196);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 197);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 198);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 199);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 200);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 201);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 202);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 203);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 204);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 205);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 206);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 207);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 208);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 209);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 210);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 211);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 212);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 213);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 214);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 215);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 216);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 217);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 218);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 219);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 220);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 221);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 222);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 223);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 224);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 225);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 226);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 227);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 228);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 229);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 230);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 231);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 232);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 233);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 234);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 235);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 236);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 237);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 238);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 239);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 240);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 241);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 242);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 243);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 244);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 245);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 246);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 247);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 248);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 249);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 250);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 251);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 252);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 253);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 254);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 255);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 256);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 257);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 258);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 259);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 260);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 261);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 262);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 263);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 264);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 265);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 266);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 267);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 268);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 269);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 270);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 271);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 272);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 273);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 274);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 275);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 276);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 277);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 278);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 279);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 280);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 281);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 282);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 283);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 284);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 285);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 286);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 287);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 288);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 289);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 290);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 291);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 292);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 293);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 294);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 295);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 296);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 297);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 298);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 299);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 300);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 301);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 302);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 303);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 304);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 305);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 306);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 307);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 308);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 309);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 310);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 311);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 312);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 313);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 314);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 315);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 316);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 317);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 318);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 319);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 320);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 321);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 322);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 323);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 324);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 325);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 326);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 327);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 328);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 329);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 330);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 331);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 332);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 333);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 334);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 335);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 336);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 337);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 338);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 339);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 340);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 341);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 342);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 343);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 344);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 345);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 346);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 347);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 348);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 349);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 350);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 351);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 352);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 353);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 354);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 355);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 356);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 357);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 358);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 359);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 360);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 361);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 362);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 363);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 364);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 365);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 366);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 367);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 368);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 369);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 370);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 371);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 372);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 373);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 374);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 375);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 376);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 377);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 378);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 379);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 380);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 381);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 382);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 383);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 384);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 385);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 386);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 387);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 388);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 389);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 390);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 391);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 392);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 393);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 394);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 395);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 396);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 397);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 398);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 399);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 400);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 401);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 402);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 403);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 404);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 405);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 406);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 407);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 408);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 409);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 410);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 411);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 412);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 413);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 414);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 415);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 416);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 417);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 418);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 419);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 420);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 421);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 422);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 423);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 424);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 425);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 426);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 427);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 428);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 429);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 430);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 431);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 432);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 433);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 434);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 435);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 436);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 437);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 438);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 439);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 440);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 441);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 442);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 443);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 444);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 445);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 446);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 447);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 448);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 449);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 450);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 451);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 452);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 453);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 454);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 455);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 456);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 457);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 458);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 459);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 460);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 461);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 462);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 463);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 464);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 465);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 466);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 467);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 468);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 469);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 470);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 471);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 472);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 473);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 474);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 475);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 476);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 477);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 478);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 479);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 480);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 481);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 482);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 483);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 484);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 485);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 486);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 487);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 488);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 489);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 490);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 491);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 492);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 493);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 494);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 495);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 496);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 497);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 498);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 499);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 500);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 501);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 502);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 503);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 504);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 505);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 506);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 507);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 508);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 509);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 510);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 511);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 512);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 513);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 514);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 515);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 516);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 517);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 518);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 519);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 520);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 521);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 522);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 523);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 524);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 525);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 526);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 527);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 528);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 529);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 530);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 531);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 532);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 533);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 534);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 535);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 536);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 537);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 538);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 539);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 540);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 541);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 542);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 543);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 544);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 545);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 546);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 547);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 548);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 549);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 550);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 551);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 552);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 553);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 554);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 555);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 556);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 557);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 558);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 559);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 560);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 561);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 562);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 563);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 564);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 565);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 566);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 567);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 568);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 569);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 570);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 571);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 572);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 573);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 574);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 575);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 576);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 577);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 578);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 579);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 580);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 581);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 582);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 583);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 584);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 585);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 586);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 587);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 588);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 589);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 590);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 591);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 592);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 593);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 594);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 595);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 596);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 597);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 598);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 599);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 600);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 601);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 602);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 603);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 604);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 605);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 606);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 607);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 608);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 609);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 610);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 611);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 612);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 613);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 614);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 615);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 616);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 617);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 618);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 619);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 620);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 621);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 622);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 623);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 624);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 625);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 626);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 627);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 628);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 629);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 630);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 631);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 632);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 633);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 634);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 635);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 636);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 637);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 638);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 639);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 640);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 641);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 642);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 643);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 644);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 645);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 646);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 647);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 648);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 649);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 650);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 651);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 652);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 653);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 654);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 655);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 656);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 657);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 658);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 659);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 660);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 661);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 662);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 663);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 664);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 665);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 666);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 667);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 668);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 669);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 670);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 671);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 672);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 673);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 674);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 675);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 676);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 677);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 678);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 679);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 680);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 681);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 682);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 683);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 684);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 685);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 686);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 687);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 688);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 689);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 690);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 691);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 692);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 693);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 694);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 695);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 696);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 697);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 698);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 699);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 700);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 701);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 702);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 703);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 704);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 705);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 706);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 707);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 708);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 709);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 710);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 711);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 712);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 713);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 714);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 715);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 716);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 717);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 718);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 719);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 720);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 721);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 722);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 723);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 724);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 725);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 726);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 727);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 728);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 729);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 730);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 731);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 732);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 733);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 734);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 735);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 736);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 737);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 738);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 739);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 740);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 741);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 742);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 743);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 744);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 745);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 746);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 747);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 748);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 749);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 750);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 751);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 752);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 753);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 754);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 755);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 756);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 757);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 758);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 759);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 760);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 761);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 762);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 763);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 764);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 765);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 766);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 767);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 768);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 769);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 770);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 771);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 772);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 773);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 774);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 775);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 776);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 777);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 778);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 779);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 780);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 781);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 782);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 783);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 784);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 785);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 786);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 787);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 788);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 789);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 790);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 791);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 792);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 793);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 794);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 795);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 796);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 797);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 798);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 799);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 800);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 801);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 802);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 803);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 804);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 805);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 806);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 807);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 808);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 809);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 810);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 811);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 812);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 813);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 814);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 815);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 816);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 817);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 818);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 819);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 820);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 821);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 822);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 823);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 824);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 825);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 826);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 827);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 828);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 829);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 830);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 831);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 832);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 833);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 834);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 835);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 836);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 837);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 838);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 839);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 840);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 841);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 842);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 843);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 844);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 845);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 846);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 847);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 848);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 849);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 850);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 851);
insert into CoachedFor (TeamName, CoachID) values ('Blackhawks', 852);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 853);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 854);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 855);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 856);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 857);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 858);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 859);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 860);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 861);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 862);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 863);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 864);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 865);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 866);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 867);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 868);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 869);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 870);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 871);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 872);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 873);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 874);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 875);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 876);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 877);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 878);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 879);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 880);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 881);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 882);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 883);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 884);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 885);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 886);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 887);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 888);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 889);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 890);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 891);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 892);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 893);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 894);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 895);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 896);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 897);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 898);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 899);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 900);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 901);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 902);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 903);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 904);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 905);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 906);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 907);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 908);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 909);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 910);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 911);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 912);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 913);
insert into CoachedFor (TeamName, CoachID) values ('Rangers', 914);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 915);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 916);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 917);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 918);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 919);
insert into CoachedFor (TeamName, CoachID) values ('Ducks', 920);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 921);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 922);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 923);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 924);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 925);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 926);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 927);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 928);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 929);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 930);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 931);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 932);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 933);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 934);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 935);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 936);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 937);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 938);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 939);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 940);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 941);
insert into CoachedFor (TeamName, CoachID) values ('Jets', 942);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 943);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 944);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 945);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 946);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 947);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 948);
insert into CoachedFor (TeamName, CoachID) values ('Oilers', 949);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 950);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 951);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 952);
insert into CoachedFor (TeamName, CoachID) values ('Sabres', 953);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 954);
insert into CoachedFor (TeamName, CoachID) values ('Maple Leafs', 955);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 956);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 957);
insert into CoachedFor (TeamName, CoachID) values ('Stars', 958);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 959);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 960);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 961);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 962);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 963);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 964);
insert into CoachedFor (TeamName, CoachID) values ('Canadiens', 965);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 966);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 967);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 968);
insert into CoachedFor (TeamName, CoachID) values ('Flyers', 969);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 970);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 971);
insert into CoachedFor (TeamName, CoachID) values ('Blue Jackets', 972);
insert into CoachedFor (TeamName, CoachID) values ('Penguins', 973);
insert into CoachedFor (TeamName, CoachID) values ('Bruins', 974);
insert into CoachedFor (TeamName, CoachID) values ('Lightning', 975);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 976);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 977);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 978);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 979);
insert into CoachedFor (TeamName, CoachID) values ('Panthers', 980);
insert into CoachedFor (TeamName, CoachID) values ('Avalanche', 981);
insert into CoachedFor (TeamName, CoachID) values ('Flames', 982);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 983);
insert into CoachedFor (TeamName, CoachID) values ('Hurricanes', 984);
insert into CoachedFor (TeamName, CoachID) values ('Islanders', 985);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 986);
insert into CoachedFor (TeamName, CoachID) values ('Predators', 987);
insert into CoachedFor (TeamName, CoachID) values ('Devils', 988);
insert into CoachedFor (TeamName, CoachID) values ('Red Wings', 989);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 990);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 991);
insert into CoachedFor (TeamName, CoachID) values ('Sharks', 992);
insert into CoachedFor (TeamName, CoachID) values ('Golden Nights', 993);
insert into CoachedFor (TeamName, CoachID) values ('Wild', 994);
insert into CoachedFor (TeamName, CoachID) values ('Capitals', 995);
insert into CoachedFor (TeamName, CoachID) values ('Senators', 996);
insert into CoachedFor (TeamName, CoachID) values ('Blues', 997);
insert into CoachedFor (TeamName, CoachID) values ('Coyotes', 998);
insert into CoachedFor (TeamName, CoachID) values ('Kings', 999);
insert into CoachedFor (TeamName, CoachID) values ('Canucks', 1000);
