insert into PlayedFor (TeamName, PlayerID) values ('Stars', 1);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 2);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 3);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 4);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 5);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 6);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 7);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 8);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 9);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 10);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 11);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 12);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 13);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 14);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 15);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 16);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 17);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 18);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 19);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 20);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 21);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 22);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 23);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 24);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 25);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 26);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 27);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 28);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 29);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 30);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 31);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 32);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 33);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 34);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 35);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 36);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 37);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 38);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 39);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 40);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 41);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 42);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 43);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 44);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 45);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 46);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 47);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 48);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 49);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 50);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 51);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 52);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 53);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 54);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 55);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 56);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 57);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 58);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 59);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 60);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 61);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 62);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 63);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 64);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 65);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 66);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 67);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 68);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 69);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 70);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 71);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 72);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 73);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 74);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 75);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 76);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 77);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 78);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 79);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 80);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 81);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 82);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 83);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 84);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 85);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 86);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 87);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 88);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 89);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 90);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 91);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 92);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 93);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 94);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 95);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 96);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 97);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 98);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 99);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 100);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 101);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 102);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 103);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 104);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 105);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 106);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 107);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 108);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 109);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 110);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 111);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 112);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 113);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 114);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 115);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 116);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 117);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 118);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 119);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 120);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 121);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 122);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 123);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 124);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 125);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 126);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 127);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 128);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 129);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 130);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 131);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 132);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 133);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 134);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 135);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 136);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 137);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 138);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 139);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 140);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 141);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 142);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 143);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 144);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 145);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 146);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 147);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 148);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 149);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 150);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 151);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 152);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 153);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 154);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 155);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 156);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 157);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 158);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 159);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 160);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 161);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 162);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 163);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 164);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 165);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 166);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 167);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 168);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 169);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 170);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 171);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 172);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 173);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 174);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 175);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 176);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 177);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 178);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 179);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 180);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 181);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 182);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 183);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 184);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 185);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 186);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 187);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 188);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 189);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 190);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 191);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 192);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 193);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 194);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 195);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 196);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 197);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 198);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 199);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 200);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 201);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 202);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 203);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 204);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 205);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 206);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 207);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 208);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 209);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 210);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 211);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 212);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 213);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 214);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 215);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 216);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 217);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 218);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 219);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 220);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 221);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 222);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 223);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 224);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 225);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 226);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 227);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 228);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 229);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 230);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 231);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 232);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 233);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 234);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 235);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 236);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 237);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 238);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 239);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 240);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 241);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 242);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 243);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 244);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 245);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 246);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 247);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 248);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 249);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 250);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 251);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 252);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 253);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 254);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 255);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 256);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 257);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 258);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 259);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 260);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 261);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 262);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 263);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 264);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 265);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 266);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 267);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 268);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 269);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 270);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 271);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 272);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 273);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 274);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 275);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 276);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 277);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 278);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 279);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 280);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 281);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 282);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 283);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 284);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 285);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 286);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 287);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 288);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 289);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 290);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 291);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 292);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 293);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 294);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 295);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 296);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 297);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 298);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 299);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 300);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 301);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 302);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 303);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 304);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 305);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 306);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 307);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 308);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 309);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 310);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 311);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 312);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 313);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 314);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 315);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 316);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 317);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 318);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 319);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 320);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 321);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 322);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 323);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 324);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 325);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 326);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 327);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 328);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 329);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 330);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 331);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 332);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 333);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 334);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 335);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 336);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 337);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 338);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 339);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 340);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 341);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 342);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 343);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 344);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 345);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 346);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 347);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 348);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 349);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 350);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 351);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 352);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 353);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 354);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 355);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 356);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 357);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 358);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 359);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 360);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 361);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 362);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 363);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 364);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 365);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 366);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 367);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 368);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 369);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 370);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 371);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 372);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 373);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 374);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 375);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 376);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 377);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 378);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 379);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 380);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 381);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 382);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 383);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 384);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 385);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 386);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 387);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 388);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 389);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 390);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 391);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 392);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 393);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 394);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 395);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 396);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 397);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 398);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 399);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 400);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 401);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 402);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 403);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 404);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 405);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 406);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 407);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 408);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 409);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 410);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 411);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 412);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 413);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 414);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 415);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 416);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 417);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 418);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 419);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 420);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 421);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 422);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 423);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 424);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 425);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 426);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 427);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 428);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 429);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 430);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 431);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 432);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 433);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 434);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 435);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 436);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 437);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 438);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 439);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 440);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 441);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 442);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 443);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 444);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 445);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 446);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 447);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 448);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 449);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 450);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 451);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 452);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 453);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 454);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 455);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 456);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 457);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 458);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 459);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 460);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 461);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 462);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 463);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 464);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 465);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 466);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 467);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 468);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 469);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 470);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 471);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 472);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 473);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 474);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 475);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 476);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 477);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 478);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 479);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 480);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 481);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 482);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 483);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 484);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 485);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 486);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 487);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 488);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 489);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 490);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 491);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 492);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 493);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 494);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 495);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 496);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 497);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 498);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 499);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 500);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 501);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 502);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 503);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 504);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 505);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 506);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 507);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 508);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 509);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 510);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 511);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 512);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 513);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 514);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 515);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 516);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 517);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 518);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 519);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 520);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 521);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 522);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 523);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 524);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 525);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 526);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 527);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 528);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 529);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 530);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 531);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 532);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 533);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 534);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 535);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 536);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 537);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 538);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 539);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 540);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 541);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 542);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 543);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 544);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 545);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 546);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 547);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 548);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 549);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 550);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 551);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 552);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 553);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 554);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 555);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 556);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 557);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 558);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 559);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 560);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 561);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 562);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 563);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 564);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 565);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 566);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 567);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 568);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 569);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 570);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 571);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 572);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 573);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 574);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 575);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 576);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 577);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 578);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 579);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 580);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 581);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 582);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 583);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 584);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 585);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 586);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 587);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 588);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 589);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 590);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 591);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 592);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 593);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 594);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 595);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 596);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 597);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 598);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 599);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 600);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 601);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 602);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 603);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 604);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 605);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 606);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 607);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 608);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 609);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 610);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 611);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 612);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 613);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 614);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 615);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 616);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 617);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 618);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 619);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 620);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 621);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 622);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 623);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 624);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 625);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 626);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 627);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 628);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 629);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 630);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 631);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 632);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 633);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 634);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 635);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 636);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 637);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 638);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 639);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 640);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 641);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 642);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 643);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 644);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 645);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 646);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 647);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 648);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 649);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 650);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 651);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 652);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 653);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 654);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 655);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 656);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 657);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 658);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 659);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 660);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 661);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 662);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 663);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 664);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 665);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 666);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 667);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 668);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 669);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 670);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 671);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 672);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 673);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 674);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 675);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 676);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 677);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 678);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 679);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 680);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 681);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 682);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 683);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 684);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 685);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 686);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 687);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 688);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 689);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 690);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 691);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 692);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 693);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 694);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 695);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 696);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 697);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 698);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 699);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 700);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 701);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 702);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 703);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 704);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 705);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 706);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 707);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 708);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 709);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 710);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 711);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 712);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 713);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 714);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 715);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 716);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 717);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 718);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 719);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 720);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 721);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 722);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 723);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 724);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 725);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 726);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 727);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 728);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 729);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 730);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 731);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 732);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 733);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 734);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 735);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 736);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 737);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 738);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 739);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 740);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 741);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 742);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 743);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 744);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 745);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 746);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 747);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 748);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 749);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 750);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 751);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 752);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 753);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 754);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 755);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 756);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 757);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 758);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 759);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 760);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 761);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 762);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 763);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 764);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 765);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 766);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 767);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 768);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 769);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 770);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 771);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 772);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 773);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 774);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 775);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 776);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 777);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 778);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 779);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 780);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 781);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 782);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 783);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 784);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 785);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 786);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 787);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 788);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 789);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 790);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 791);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 792);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 793);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 794);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 795);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 796);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 797);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 798);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 799);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 800);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 801);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 802);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 803);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 804);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 805);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 806);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 807);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 808);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 809);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 810);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 811);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 812);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 813);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 814);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 815);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 816);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 817);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 818);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 819);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 820);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 821);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 822);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 823);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 824);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 825);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 826);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 827);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 828);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 829);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 830);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 831);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 832);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 833);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 834);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 835);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 836);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 837);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 838);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 839);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 840);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 841);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 842);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 843);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 844);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 845);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 846);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 847);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 848);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 849);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 850);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 851);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 852);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 853);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 854);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 855);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 856);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 857);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 858);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 859);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 860);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 861);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 862);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 863);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 864);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 865);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 866);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 867);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 868);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 869);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 870);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 871);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 872);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 873);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 874);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 875);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 876);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 877);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 878);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 879);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 880);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 881);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 882);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 883);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 884);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 885);
insert into PlayedFor (TeamName, PlayerID) values ('Jets', 886);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 887);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 888);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 889);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 890);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 891);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 892);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 893);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 894);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 895);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 896);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 897);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 898);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 899);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 900);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 901);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 902);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 903);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 904);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 905);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 906);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 907);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 908);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 909);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 910);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 911);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 912);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 913);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 914);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 915);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 916);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 917);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 918);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 919);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 920);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 921);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 922);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 923);
insert into PlayedFor (TeamName, PlayerID) values ('Coyotes', 924);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 925);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 926);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 927);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 928);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 929);
insert into PlayedFor (TeamName, PlayerID) values ('Bruins', 930);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 931);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 932);
insert into PlayedFor (TeamName, PlayerID) values ('Sabres', 933);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 934);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 935);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 936);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 937);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 938);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 939);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 940);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 941);
insert into PlayedFor (TeamName, PlayerID) values ('Blackhawks', 942);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 943);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 944);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 945);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 946);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 947);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 948);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 949);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 950);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 951);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 952);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 953);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 954);
insert into PlayedFor (TeamName, PlayerID) values ('Islanders', 955);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 956);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 957);
insert into PlayedFor (TeamName, PlayerID) values ('Kings', 958);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 959);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 960);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 961);
insert into PlayedFor (TeamName, PlayerID) values ('Capitals', 962);
insert into PlayedFor (TeamName, PlayerID) values ('Oilers', 963);
insert into PlayedFor (TeamName, PlayerID) values ('Wild', 964);
insert into PlayedFor (TeamName, PlayerID) values ('Predators', 965);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 966);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 967);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 968);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 969);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 970);
insert into PlayedFor (TeamName, PlayerID) values ('Flyers', 971);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 972);
insert into PlayedFor (TeamName, PlayerID) values ('Stars', 973);
insert into PlayedFor (TeamName, PlayerID) values ('Panthers', 974);
insert into PlayedFor (TeamName, PlayerID) values ('Senators', 975);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 976);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 977);
insert into PlayedFor (TeamName, PlayerID) values ('Ducks', 978);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 979);
insert into PlayedFor (TeamName, PlayerID) values ('Hurricanes', 980);
insert into PlayedFor (TeamName, PlayerID) values ('Penguins', 981);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 982);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 983);
insert into PlayedFor (TeamName, PlayerID) values ('Rangers', 984);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 985);
insert into PlayedFor (TeamName, PlayerID) values ('Canucks', 986);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 987);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 988);
insert into PlayedFor (TeamName, PlayerID) values ('Blue Jackets', 989);
insert into PlayedFor (TeamName, PlayerID) values ('Devils', 990);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 991);
insert into PlayedFor (TeamName, PlayerID) values ('Sharks', 992);
insert into PlayedFor (TeamName, PlayerID) values ('Maple Leafs', 993);
insert into PlayedFor (TeamName, PlayerID) values ('Golden Nights', 994);
insert into PlayedFor (TeamName, PlayerID) values ('Lightning', 995);
insert into PlayedFor (TeamName, PlayerID) values ('Avalanche', 996);
insert into PlayedFor (TeamName, PlayerID) values ('Red Wings', 997);
insert into PlayedFor (TeamName, PlayerID) values ('Blues', 998);
insert into PlayedFor (TeamName, PlayerID) values ('Canadiens', 999);
insert into PlayedFor (TeamName, PlayerID) values ('Flames', 1000);
